#!/usr/bin/env python3
"""Dump the ``Settings`` schema as the markdown matrix consumed by ``docs/environment.md``.

Walks every field on ``src.common.settings.settings`` (which subclasses
``CoreSettings``) and emits a single markdown table: field name, type,
required vs optional, default, validator, source notes. The same script
acts as a drift guard in ``--check`` mode: it diffs its rendered output
against ``docs/environment.md`` and exits non-zero on mismatch so a
forgotten doc update fails CI rather than silently rotting.

Run modes::

    python scripts/dump_settings_schema.py             # print to stdout
    python scripts/dump_settings_schema.py --write     # overwrite docs/environment.md
    python scripts/dump_settings_schema.py --check     # exit 1 if docs are stale

Source of truth is the ``Settings`` class — never hand-edit the table
section of ``docs/environment.md``. Hand-written prose around the table
is preserved verbatim by the ``BEGIN AUTO`` / ``END AUTO`` markers.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC_PATH = ROOT / "docs" / "environment.md"

BEGIN_MARKER = (
    "<!-- BEGIN AUTO: settings table — generated by scripts/dump_settings_schema.py -->"
)
END_MARKER = "<!-- END AUTO -->"


def _format_default(value: object) -> str:
    """Render a default value for the markdown column.

    Args:
        value: Pydantic's resolved default (sentinel ``PydanticUndefined``
            for required fields).

    Returns:
        ``"—"`` for required (no default), ``"None"`` for ``None``,
        quoted form for strings, ``repr`` otherwise.
    """
    from pydantic_core import PydanticUndefined  # type: ignore[import-not-found]

    if value is PydanticUndefined:
        return "—"
    if value is None:
        return "`None`"
    if isinstance(value, str):
        return f"`{value!r}`"
    return f"`{value!r}`"


def render_table() -> str:
    """Return the settings matrix as a markdown table.

    Returns:
        Multi-line markdown string framed by the AUTO markers.
    """
    # Imported lazily so a misconfigured settings load doesn't kill the
    # script's import phase.
    from src.common.settings import Settings  # noqa: PLC0415

    lines = [
        BEGIN_MARKER,
        "",
        "| Field | Type | Required | Default | Description |",
        "|---|---|---|---|---|",
    ]
    for name, info in Settings.model_fields.items():
        annotation = info.annotation
        type_repr = getattr(annotation, "__name__", None) or str(annotation)
        required = "✅" if info.is_required() else "—"
        default = _format_default(info.default)
        desc = (info.description or "").replace("|", "\\|").replace("\n", " ")
        lines.append(f"| `{name}` | `{type_repr}` | {required} | {default} | {desc} |")
    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def render_full_doc() -> str:
    """Compose the full ``docs/environment.md`` body, table included.

    Returns:
        The complete document — preserved hand-written prose plus the
        regenerated table — ready to write back.
    """
    table = render_table()
    if DOC_PATH.exists():
        existing = DOC_PATH.read_text(encoding="utf-8")
        if BEGIN_MARKER in existing and END_MARKER in existing:
            before, _, rest = existing.partition(BEGIN_MARKER)
            _, _, after = rest.partition(END_MARKER)
            return f"{before}{table}{after}"
    # First-run fallback: ship a header + the autogenerated table.
    header = (
        "# Environment & configuration\n\n"
        "Every setting consumed by the application. Source of truth is\n"
        "`src/common/settings.Settings` (subclasses `CoreSettings`); the\n"
        "table below is regenerated by `scripts/dump_settings_schema.py`.\n\n"
        "Resolution order (highest → lowest):\n\n"
        "1. AWS Secrets Manager (when `AWS_SECRET_NAME` is set)\n"
        "2. Environment variables\n"
        "3. `.env` file (gitignored)\n"
        "4. Field defaults\n\n"
        "Do not hand-edit the table between the `BEGIN AUTO` / `END AUTO`\n"
        "markers — run the script instead. Hand-written prose around the\n"
        "markers is preserved.\n\n"
    )
    return header + table + "\n"


def main() -> int:
    """Drive the three modes from the command line.

    Returns:
        ``0`` on success, ``1`` when ``--check`` finds drift.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--write", action="store_true", help="overwrite docs/environment.md"
    )
    group.add_argument("--check", action="store_true", help="exit 1 if docs are stale")
    args = parser.parse_args()

    rendered = render_full_doc()

    if args.write:
        DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
        DOC_PATH.write_text(rendered, encoding="utf-8")
        print(f"wrote {DOC_PATH.relative_to(ROOT)}")
        return 0

    if args.check:
        if not DOC_PATH.exists():
            print(f"{DOC_PATH.relative_to(ROOT)} missing; run --write", file=sys.stderr)
            return 1
        current = DOC_PATH.read_text(encoding="utf-8")
        if current != rendered:
            print(
                f"{DOC_PATH.relative_to(ROOT)} is stale; run "
                "`python scripts/dump_settings_schema.py --write` and commit.",
                file=sys.stderr,
            )
            return 1
        return 0

    # Default: print to stdout.
    print(rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main())
